#docker-compose up
#docker-compose up --build

version: "3.7"
services:

  apache: 
    build: .
    ports:
      - 80:80
    links:
      - db:db
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306