#docker-compose up
#docker-compose up --build

version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: billet-simple
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
  apache:
    build: .
    ports:
      - 80:80
    links:
      - db